require_relative 'db_config'
require 'fog'
require 'carrierwave'
require 'carrierwave/orm/activerecord'
require_relative 'models/animal'
require_relative 'models/user'
require_relative 'models/state'
require_relative 'models/city'
require_relative 'models/dog_breed'
require_relative 'models/match'


DogBreed.create(name: 'Affenpinscher');
DogBreed.create(name: 'Afghan Hound');
DogBreed.create(name: 'Airedale Terrier');
DogBreed.create(name: 'Akita');
DogBreed.create(name: 'Alaskan Malamute');
DogBreed.create(name: 'Standard American Eskimo Dog');
DogBreed.create(name: 'Miniature American Eskimo Dog');
DogBreed.create(name: 'Toy American Eskimo Dog');
DogBreed.create(name: 'American Foxhound');
DogBreed.create(name: 'American Staffordshire Terrier');
DogBreed.create(name: 'American Water Spaniel');
DogBreed.create(name: 'Anatolian Shepherd Dog');
DogBreed.create(name: 'Australian Cattle Dog');
DogBreed.create(name: 'Australian Shepherd');
DogBreed.create(name: 'Australian Terrier');
DogBreed.create(name: 'Basenji');
DogBreed.create(name: 'Basset Hound');
DogBreed.create(name: 'Beagle');
DogBreed.create(name: 'Bearded Collie');
DogBreed.create(name: 'Beauceron');
DogBreed.create(name: 'Bedlington Terrier');
DogBreed.create(name: 'Belgian Malinois');
DogBreed.create(name: 'Belgian Sheepdog');
DogBreed.create(name: 'Belgian Tervuren');
DogBreed.create(name: 'Bernese Mountain Dog');
DogBreed.create(name: 'Bichon Frise');
DogBreed.create(name: 'Black and Tan Coonhound');
DogBreed.create(name: 'Black Russian Terrier');
DogBreed.create(name: 'Bloodhound');
DogBreed.create(name: 'Border Collie');
DogBreed.create(name: 'Border Terrier');
DogBreed.create(name: 'Borzoi');
DogBreed.create(name: 'Boston Terrier');
DogBreed.create(name: 'Bouvier des Flandres');
DogBreed.create(name: 'Boxer');
DogBreed.create(name: 'Briard');
DogBreed.create(name: 'Brittany');
DogBreed.create(name: 'Brussels Griffon');
DogBreed.create(name: 'Bulldog');
DogBreed.create(name: 'Bullmastiff');
DogBreed.create(name: 'Bull Terrier');
DogBreed.create(name: 'Cairn Terrier');
DogBreed.create(name: 'Canaan Dog');
DogBreed.create(name: 'Cardigan Welsh Corgi');
DogBreed.create(name: 'Cavalier King Charles Spaniel');
DogBreed.create(name: 'Chesapeake Bay Retriever');
DogBreed.create(name: 'Chihuahua');
DogBreed.create(name: 'Chinese Crested');
DogBreed.create(name: 'Chinese Shar-Pei');
DogBreed.create(name: 'Chow Chow');
DogBreed.create(name: 'Clumber Spaniel');
DogBreed.create(name: 'Cocker Spaniel');
DogBreed.create(name: 'Collie');
DogBreed.create(name: 'Curly-Coated Retriever');
DogBreed.create(name: 'Dachshund');
DogBreed.create(name: 'Dalmatian');
DogBreed.create(name: 'Dandie Dinmont Terrier');
DogBreed.create(name: 'Doberman Pinscher');
DogBreed.create(name: 'Dogue de Bordeaux');
DogBreed.create(name: 'English Cocker Spaniel');
DogBreed.create(name: 'English Foxhound');
DogBreed.create(name: 'English Setter');
DogBreed.create(name: 'English Springer Spaniel');
DogBreed.create(name: 'English Toy Spaniel');
DogBreed.create(name: 'Field Spaniel');
DogBreed.create(name: 'Finnish Spitz');
DogBreed.create(name: 'Flat-Coated Retriever');
DogBreed.create(name: 'French Bulldog');
DogBreed.create(name: 'German Pinscher');
DogBreed.create(name: 'German Shepherd Dog');
DogBreed.create(name: 'German Shorthaired Pointer');
DogBreed.create(name: 'German Wirehaired Pointer');
DogBreed.create(name: 'Giant Schnauzer');
DogBreed.create(name: 'Glen of Imaal Terrier');
DogBreed.create(name: 'Golden Retriever');
DogBreed.create(name: 'Gordon Setter');
DogBreed.create(name: 'Great Dane');
DogBreed.create(name: 'Greater Swiss Mountain Dog');
DogBreed.create(name: 'Great Pyrenees');
DogBreed.create(name: 'Greyhound');
DogBreed.create(name: 'Harrier');
DogBreed.create(name: 'Havanese');
DogBreed.create(name: 'Ibizan Hound');
DogBreed.create(name: 'Irish Setter');
DogBreed.create(name: 'Irish Terrier');
DogBreed.create(name: 'Irish Water Spaniel');
DogBreed.create(name: 'Irish Wolfhound');
DogBreed.create(name: 'Italian Greyhound');
DogBreed.create(name: 'Jack Russell Terrier');
DogBreed.create(name: 'Japanese Chin');
DogBreed.create(name: 'Keeshond');
DogBreed.create(name: 'Kerry Blue Terrier');
DogBreed.create(name: 'Komondor');
DogBreed.create(name: 'Kuvasz');
DogBreed.create(name: 'Labrador Retriever');
DogBreed.create(name: 'Lakeland Terrier');
DogBreed.create(name: 'Lhasa Apso');
DogBreed.create(name: 'Lowchen');
DogBreed.create(name: 'Maltese');
DogBreed.create(name: 'Standard Manchester Terrier');
DogBreed.create(name: 'Mastiff');
DogBreed.create(name: 'Miniature Bull Terrier');
DogBreed.create(name: 'Miniature Pinscher');
DogBreed.create(name: 'Miniature Poodle');
DogBreed.create(name: 'Miniature Schnauzer');
DogBreed.create(name: 'Neapolitan Mastiff');
DogBreed.create(name: 'Newfoundland');
DogBreed.create(name: 'Norfolk Terrier');
DogBreed.create(name: 'Norwegian Elkhound');
DogBreed.create(name: 'Norwich Terrier');
DogBreed.create(name: 'Nova Scotia Duck Tolling Retriever');
DogBreed.create(name: 'Old English Sheepdog');
DogBreed.create(name: 'Otterhound');
DogBreed.create(name: 'Papillon');
DogBreed.create(name: 'Parson Russell Terrier');
DogBreed.create(name: 'Pembroke Welsh Corgi');
DogBreed.create(name: 'Petit Basset Griffon Vendeen');
DogBreed.create(name: 'Pharaoh Hound');
DogBreed.create(name: 'Plott');
DogBreed.create(name: 'Pointer');
DogBreed.create(name: 'Polish Lowland Sheepdog');
DogBreed.create(name: 'Pomeranian');
DogBreed.create(name: 'Portuguese Water Dog');
DogBreed.create(name: 'Pug');
DogBreed.create(name: 'Puli');
DogBreed.create(name: 'Rhodesian Ridgeback');
DogBreed.create(name: 'Rottweiler');
DogBreed.create(name: 'Saint Bernard');
DogBreed.create(name: 'Saluki');
DogBreed.create(name: 'Samoyed');
DogBreed.create(name: 'Schipperke');
DogBreed.create(name: 'Scottish Deerhound');
DogBreed.create(name: 'Scottish Terrier');
DogBreed.create(name: 'Sealyham Terrier');
DogBreed.create(name: 'Shetland Sheepdog');
DogBreed.create(name: 'Shiba Inu');
DogBreed.create(name: 'Shih Tzu');
DogBreed.create(name: 'Siberian Husky');
DogBreed.create(name: 'Silky Terrier');
DogBreed.create(name: 'Skye Terrier');
DogBreed.create(name: 'Smooth Fox Terrier');
DogBreed.create(name: 'Soft Coated Wheaten Terrier');
DogBreed.create(name: 'Spinone Italiano');
DogBreed.create(name: 'Staffordshire Bull Terrier');
DogBreed.create(name: 'Standard Poodle');
DogBreed.create(name: 'Standard Schnauzer');
DogBreed.create(name: 'Sussex Spaniel');
DogBreed.create(name: 'Swedish Vallhund');
DogBreed.create(name: 'Tibetan Mastiff');
DogBreed.create(name: 'Tibetan Spaniel');
DogBreed.create(name: 'Tibetan Terrier');
DogBreed.create(name: 'Toy Fox Terrier');
DogBreed.create(name: 'Toy Manchester Terrier');
DogBreed.create(name: 'Toy Poodle');
DogBreed.create(name: 'Vizsla');
DogBreed.create(name: 'Weimaraner');
DogBreed.create(name: 'Welsh Springer Spaniel');
DogBreed.create(name: 'Welsh Terrier');
DogBreed.create(name: 'West Highland White Terrier');
DogBreed.create(name: 'Whippet');
DogBreed.create(name: 'Wire Fox Terrier');
DogBreed.create(name: 'Wirehaired Pointing Griffon');
DogBreed.create(name: 'Yorkshire Terrier');

nsw = State.create(name: 'New South Wales')
qld = State.create(name: 'Queensland')
sa = State.create(name: 'South Australia')
tas = State.create(name: 'Tasmania')
vic = State.create(name: 'Victoria')
wa = State.create(name: 'Western Australia')
act = State.create(name: 'Australian Capital Territory')
nt = State.create(name: 'Northern Territory')


City.create(name: 'Sydney',state_id: nsw.id);
City.create(name: 'Albury', state_id: nsw.id);
City.create(name: 'Armidale', state_id: nsw.id);
City.create(name: 'Bathurst', state_id: nsw.id);
City.create(name: 'Blue Mountains', state_id: nsw.id);
City.create(name: 'Broken', state_id: nsw.id);
City.create(name: 'Campbelltown', state_id: nsw.id);
City.create(name: 'Cessnock', state_id: nsw.id);
City.create(name: 'Dubbo', state_id: nsw.id);
City.create(name: 'Goulburn', state_id: nsw.id);
City.create(name: 'Grafton', state_id: nsw.id);
City.create(name: 'Lithgow', state_id: nsw.id);
City.create(name: 'Liverpool', state_id: nsw.id);
City.create(name: 'Newcastle', state_id: nsw.id);
City.create(name: 'Orange', state_id: nsw.id);
City.create(name: 'Parramatta', state_id: nsw.id);
City.create(name: 'Penrith', state_id: nsw.id);
City.create(name: 'Queanbeyan', state_id: nsw.id);
City.create(name: 'Tamworth', state_id: nsw.id);
City.create(name: 'Wagga', state_id: nsw.id);
City.create(name: 'Wollongong', state_id: nsw.id);

City.create(name: 'Brisbane', state_id: qld.id);
City.create(name: 'Bundaberg', state_id: qld.id);
City.create(name: 'Caboolture', state_id: qld.id);
City.create(name: 'Cairns', state_id: qld.id);
City.create(name: 'Caloundra', state_id: qld.id);
City.create(name: 'Gladstone', state_id: qld.id);
City.create(name: 'Gold Coast');
City.create(name: 'Gympie', state_id: qld.id);
City.create(name: 'Hervey', state_id: qld.id);
City.create(name: 'Ipswich', state_id: qld.id);
City.create(name: 'Logan', state_id: qld.id);
City.create(name: 'Mackay', state_id: qld.id);
City.create(name: 'Maryborough', state_id: qld.id);
City.create(name: 'Mount', state_id: qld.id);
City.create(name: 'Rockhampton', state_id: qld.id);
City.create(name: 'Sunshine', state_id: qld.id);
City.create(name: 'Toowoomba', state_id: qld.id);
City.create(name: 'Townsville', state_id: qld.id);

City.create(name: 'Adelaide', state_id: sa.id);
City.create(name: 'Mount Barker', state_id: sa.id);
City.create(name: 'Mount Gambier', state_id: sa.id);
City.create(name: 'Murray Bridge', state_id: sa.id);
City.create(name: 'Port Adelaide', state_id: sa.id);
City.create(name: 'Port Augusta', state_id: sa.id);
City.create(name: 'Port Pirie', state_id: sa.id);
City.create(name: 'Port Lincoln', state_id: sa.id);
City.create(name: 'Victor Harbor', state_id: sa.id);
City.create(name: 'Whyalla', state_id: sa.id);

City.create(name: 'hobart', state_id: tas.id);
City.create(name: 'Burnie', state_id: tas.id);
City.create(name: 'Devonport', state_id: tas.id);
City.create(name: 'Launceston', state_id: tas.id);

City.create(name: 'Melbourne', state_id: vic.id);
City.create(name: 'Geelong', state_id: vic.id);
City.create(name: 'Ballarat', state_id: vic.id);
City.create(name: 'Bendigo', state_id: vic.id);
City.create(name: 'Melton', state_id: vic.id);
City.create(name: 'Pakenham', state_id: vic.id);
City.create(name: 'Mildura', state_id: vic.id);
City.create(name: 'Wodonga', state_id: vic.id);
City.create(name: 'Warrnambool', state_id: vic.id);
City.create(name: 'Traralgon', state_id: vic.id);
City.create(name: 'Wangaratta', state_id: vic.id);
City.create(name: 'Ocean', state_id: vic.id);
City.create(name: 'Moe', state_id: vic.id);
City.create(name: 'Horsham', state_id: vic.id);
City.create(name: 'Bacchus', state_id: vic.id);
City.create(name: 'Morwell', state_id: vic.id);
City.create(name: 'Torquay', state_id: vic.id);
City.create(name: 'Warragul', state_id: vic.id);
City.create(name: 'Sale', state_id: vic.id);
City.create(name: 'Echuca', state_id: vic.id);
City.create(name: 'Bairnsdale', state_id: vic.id);
City.create(name: 'Colac', state_id: vic.id);
City.create(name: 'Lara', state_id: vic.id);
City.create(name: 'Drysdale', state_id: vic.id);
City.create(name: 'Portland', state_id: vic.id);
City.create(name: 'Swan', state_id: vic.id);
City.create(name: 'Leopold', state_id: vic.id);
City.create(name: 'Drouin', state_id: vic.id);
City.create(name: 'Hamilton', state_id: vic.id);
City.create(name: 'Benalla', state_id: vic.id);
City.create(name: 'Castlemaine', state_id: vic.id);
City.create(name: 'Gisborne', state_id: vic.id);
City.create(name: 'Healesville', state_id: vic.id);
City.create(name: 'Wallan', state_id: vic.id);
City.create(name: 'Wonthaggi', state_id: vic.id);
City.create(name: 'Maryborough', state_id: vic.id);
City.create(name: 'Ararat', state_id: vic.id);
City.create(name: 'Yarrawonga', state_id: vic.id);
City.create(name: 'Kilmore', state_id: vic.id);
City.create(name: 'Lakes', state_id: vic.id);
City.create(name: 'Seymour', state_id: vic.id);
City.create(name: 'Stawell', state_id: vic.id);
City.create(name: 'Kyabram', state_id: vic.id);
City.create(name: 'Cobram', state_id: vic.id);
City.create(name: 'Maffra', state_id: vic.id);
City.create(name: 'Leongatha', state_id: vic.id);
City.create(name: 'Churchill', state_id: vic.id);
City.create(name: 'Kyneton', state_id: vic.id);

City.create(name: 'Perth', state_id: wa.id);
City.create(name: 'Albany', state_id: wa.id);
City.create(name: 'Bunbury', state_id: wa.id);
City.create(name: 'Busselton', state_id: wa.id);
City.create(name: 'Fremantle', state_id: wa.id);
City.create(name: 'Geraldton', state_id: wa.id);
City.create(name: 'Joondalup', state_id: wa.id);
City.create(name: 'Kalgoorlie', state_id: wa.id);
City.create(name: 'Mandurah', state_id: wa.id);
City.create(name: 'Karratha', state_id: wa.id);
City.create(name: 'Rockingham', state_id: wa.id);

City.create(name: 'Belconnen', state_id: act.id);
City.create(name: 'Bruce', state_id: act.id);
City.create(name: 'Canberra', state_id: act.id);
City.create(name: 'Evatt', state_id: act.id);
City.create(name: 'Giralang', state_id: act.id);
City.create(name: 'Hawker', state_id: act.id);
City.create(name: 'Kaleen', state_id: act.id);
City.create(name: 'Lawson', state_id: act.id);
City.create(name: 'Melba', state_id: act.id);
City.create(name: 'Spence', state_id: act.id);
City.create(name: 'Tuggeranong', state_id: act.id);
City.create(name: 'Weston Creek', state_id: act.id);

City.create(name: 'Darwin', state_id: nt.id);
City.create(name: 'Palmerston-East Arm', state_id: nt.id);
City.create(name: 'Alice Springs', state_id: nt.id);
City.create(name: 'Litchfield', state_id: nt.id);
City.create(name: 'Katherine', state_id: nt.id);
City.create(name: 'Nhulunbuy', state_id: nt.id);
City.create(name: 'Tennant Creek', state_id: nt.id);
City.create(name: 'Wadeye / Victoria-Daly', state_id: nt.id);
City.create(name: 'Jabiru', state_id: nt.id);
City.create(name: 'Yulara', state_id: nt.id);
