require_relative 'db_config'
require 'fog'
require 'carrierwave'
require 'carrierwave/orm/activerecord'
require_relative 'models/animal'
require_relative 'models/user'
require_relative 'models/state'
require_relative 'models/city'
require_relative 'models/dog_breed'
require_relative 'models/match'


DogBreed.create(name: 'Affenpinscher');
DogBreed.create(name: 'Afghan Hound');
DogBreed.create(name: 'Airedale Terrier');
DogBreed.create(name: 'Akita');
DogBreed.create(name: 'Alaskan Malamute');
DogBreed.create(name: 'Standard American Eskimo Dog');
DogBreed.create(name: 'Miniature American Eskimo Dog');
DogBreed.create(name: 'Toy American Eskimo Dog');
DogBreed.create(name: 'American Foxhound');
DogBreed.create(name: 'American Staffordshire Terrier');
DogBreed.create(name: 'American Water Spaniel');
DogBreed.create(name: 'Anatolian Shepherd Dog');
DogBreed.create(name: 'Australian Cattle Dog');
DogBreed.create(name: 'Australian Shepherd');
DogBreed.create(name: 'Australian Terrier');
DogBreed.create(name: 'Basenji');
DogBreed.create(name: 'Basset Hound');
DogBreed.create(name: 'Beagle');
DogBreed.create(name: 'Bearded Collie');
DogBreed.create(name: 'Beauceron');
DogBreed.create(name: 'Bedlington Terrier');
DogBreed.create(name: 'Belgian Malinois');
DogBreed.create(name: 'Belgian Sheepdog');
DogBreed.create(name: 'Belgian Tervuren');
DogBreed.create(name: 'Bernese Mountain Dog');
DogBreed.create(name: 'Bichon Frise');
DogBreed.create(name: 'Black and Tan Coonhound');
DogBreed.create(name: 'Black Russian Terrier');
DogBreed.create(name: 'Bloodhound');
DogBreed.create(name: 'Border Collie');
DogBreed.create(name: 'Border Terrier');
DogBreed.create(name: 'Borzoi');
DogBreed.create(name: 'Boston Terrier');
DogBreed.create(name: 'Bouvier des Flandres');
DogBreed.create(name: 'Boxer');
DogBreed.create(name: 'Briard');
DogBreed.create(name: 'Brittany');
DogBreed.create(name: 'Brussels Griffon');
DogBreed.create(name: 'Bulldog');
DogBreed.create(name: 'Bullmastiff');
DogBreed.create(name: 'Bull Terrier');
DogBreed.create(name: 'Cairn Terrier');
DogBreed.create(name: 'Canaan Dog');
DogBreed.create(name: 'Cardigan Welsh Corgi');
DogBreed.create(name: 'Cavalier King Charles Spaniel');
DogBreed.create(name: 'Chesapeake Bay Retriever');
DogBreed.create(name: 'Chihuahua');
DogBreed.create(name: 'Chinese Crested');
DogBreed.create(name: 'Chinese Shar-Pei');
DogBreed.create(name: 'Chow Chow');
DogBreed.create(name: 'Clumber Spaniel');
DogBreed.create(name: 'Cocker Spaniel');
DogBreed.create(name: 'Collie');
DogBreed.create(name: 'Curly-Coated Retriever');
DogBreed.create(name: 'Dachshund');
DogBreed.create(name: 'Dalmatian');
DogBreed.create(name: 'Dandie Dinmont Terrier');
DogBreed.create(name: 'Doberman Pinscher');
DogBreed.create(name: 'Dogue de Bordeaux');
DogBreed.create(name: 'English Cocker Spaniel');
DogBreed.create(name: 'English Foxhound');
DogBreed.create(name: 'English Setter');
DogBreed.create(name: 'English Springer Spaniel');
DogBreed.create(name: 'English Toy Spaniel');
DogBreed.create(name: 'Field Spaniel');
DogBreed.create(name: 'Finnish Spitz');
DogBreed.create(name: 'Flat-Coated Retriever');
DogBreed.create(name: 'French Bulldog');
DogBreed.create(name: 'German Pinscher');
DogBreed.create(name: 'German Shepherd Dog');
DogBreed.create(name: 'German Shorthaired Pointer');
DogBreed.create(name: 'German Wirehaired Pointer');
DogBreed.create(name: 'Giant Schnauzer');
DogBreed.create(name: 'Glen of Imaal Terrier');
DogBreed.create(name: 'Golden Retriever');
DogBreed.create(name: 'Gordon Setter');
DogBreed.create(name: 'Great Dane');
DogBreed.create(name: 'Greater Swiss Mountain Dog');
DogBreed.create(name: 'Great Pyrenees');
DogBreed.create(name: 'Greyhound');
DogBreed.create(name: 'Harrier');
DogBreed.create(name: 'Havanese');
DogBreed.create(name: 'Ibizan Hound');
DogBreed.create(name: 'Irish Setter');
DogBreed.create(name: 'Irish Terrier');
DogBreed.create(name: 'Irish Water Spaniel');
DogBreed.create(name: 'Irish Wolfhound');
DogBreed.create(name: 'Italian Greyhound');
DogBreed.create(name: 'Jack Russell Terrier');
DogBreed.create(name: 'Japanese Chin');
DogBreed.create(name: 'Keeshond');
DogBreed.create(name: 'Kerry Blue Terrier');
DogBreed.create(name: 'Komondor');
DogBreed.create(name: 'Kuvasz');
DogBreed.create(name: 'Labrador Retriever');
DogBreed.create(name: 'Lakeland Terrier');
DogBreed.create(name: 'Lhasa Apso');
DogBreed.create(name: 'Lowchen');
DogBreed.create(name: 'Maltese');
DogBreed.create(name: 'Standard Manchester Terrier');
DogBreed.create(name: 'Mastiff');
DogBreed.create(name: 'Miniature Bull Terrier');
DogBreed.create(name: 'Miniature Pinscher');
DogBreed.create(name: 'Miniature Poodle');
DogBreed.create(name: 'Miniature Schnauzer');
DogBreed.create(name: 'Neapolitan Mastiff');
DogBreed.create(name: 'Newfoundland');
DogBreed.create(name: 'Norfolk Terrier');
DogBreed.create(name: 'Norwegian Elkhound');
DogBreed.create(name: 'Norwich Terrier');
DogBreed.create(name: 'Nova Scotia Duck Tolling Retriever');
DogBreed.create(name: 'Old English Sheepdog');
DogBreed.create(name: 'Otterhound');
DogBreed.create(name: 'Papillon');
DogBreed.create(name: 'Parson Russell Terrier');
DogBreed.create(name: 'Pembroke Welsh Corgi');
DogBreed.create(name: 'Petit Basset Griffon Vendeen');
DogBreed.create(name: 'Pharaoh Hound');
DogBreed.create(name: 'Plott');
DogBreed.create(name: 'Pointer');
DogBreed.create(name: 'Polish Lowland Sheepdog');
DogBreed.create(name: 'Pomeranian');
DogBreed.create(name: 'Portuguese Water Dog');
DogBreed.create(name: 'Pug');
DogBreed.create(name: 'Puli');
DogBreed.create(name: 'Rhodesian Ridgeback');
DogBreed.create(name: 'Rottweiler');
DogBreed.create(name: 'Saint Bernard');
DogBreed.create(name: 'Saluki');
DogBreed.create(name: 'Samoyed');
DogBreed.create(name: 'Schipperke');
DogBreed.create(name: 'Scottish Deerhound');
DogBreed.create(name: 'Scottish Terrier');
DogBreed.create(name: 'Sealyham Terrier');
DogBreed.create(name: 'Shetland Sheepdog');
DogBreed.create(name: 'Shiba Inu');
DogBreed.create(name: 'Shih Tzu');
DogBreed.create(name: 'Siberian Husky');
DogBreed.create(name: 'Silky Terrier');
DogBreed.create(name: 'Skye Terrier');
DogBreed.create(name: 'Smooth Fox Terrier');
DogBreed.create(name: 'Soft Coated Wheaten Terrier');
DogBreed.create(name: 'Spinone Italiano');
DogBreed.create(name: 'Staffordshire Bull Terrier');
DogBreed.create(name: 'Standard Poodle');
DogBreed.create(name: 'Standard Schnauzer');
DogBreed.create(name: 'Sussex Spaniel');
DogBreed.create(name: 'Swedish Vallhund');
DogBreed.create(name: 'Tibetan Mastiff');
DogBreed.create(name: 'Tibetan Spaniel');
DogBreed.create(name: 'Tibetan Terrier');
DogBreed.create(name: 'Toy Fox Terrier');
DogBreed.create(name: 'Toy Manchester Terrier');
DogBreed.create(name: 'Toy Poodle');
DogBreed.create(name: 'Vizsla');
DogBreed.create(name: 'Weimaraner');
DogBreed.create(name: 'Welsh Springer Spaniel');
DogBreed.create(name: 'Welsh Terrier');
DogBreed.create(name: 'West Highland White Terrier');
DogBreed.create(name: 'Whippet');
DogBreed.create(name: 'Wire Fox Terrier');
DogBreed.create(name: 'Wirehaired Pointing Griffon');
DogBreed.create(name: 'Yorkshire Terrier');
